parameters:
    ob_campaign.snapshot.class: Ob\CampaignBundle\Utils\Snapshot
    ob_campaign.premailer.class: Ob\CampaignBundle\Premailer\Premailer
    ob_campaign.binary_path: /usr/local/bin/wkhtmltoimage
    ob_campaign.image_folder: %kernel.root_dir%/../web/images/campaign/

services:
    ob_campaign.snapshot:
        class: %ob_campaign.snapshot.class%
        arguments: [%ob_campaign.image_folder%, %ob_campaign.binary_path%]

    ob_campaign.premailer:
        class: %ob_campaign.premailer.class%
